from typing import Any

import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scipy.sparse as sp
import seaborn as sns
from anndata import AnnData
from matplotlib.axes import Axes


def differential_composition(
    adata_sc: AnnData,
    stat_key: str = "shears_stats",
    *,
    metric: str = "median_wald_stat",
    bias_corrected: bool = True,
    negative_label: str | None = None,
    positive_label: str | None = None,
    fdr_threshold: float = 0.01,
    exclude_ns: bool = False,
    sort_by: list[str] | None = None,
    vmin: float | str | None = "p5",
    vmax: float | str | None = "p95",
    min_convergence: float = 0.0,
    show_convergence: bool = True,
    ax: Axes | None = None,
    show: bool | None = None,
    **kwargs: Any,
) -> Axes | None:
    """\
    Visualize differential composition statistics as a divergent boxplot.

    This plotting function reads the aggregated Wald statistics and biological 
    metadata generated by `tl.differential_composition`. It colors the boxes based 
    on the magnitude of the effect and allows for dynamic thresholding based on 
    model convergence and FDR significance.

    Parameters
    ----------
    adata_sc
        Annotated data matrix.
    stat_key
        Key in `adata_sc.uns` where the differential composition results are stored.
    metric
        The statistical metric to plot on the x-axis (defaults to the Wald statistic).
    bias_corrected
        If `True`, attempts to plot the version of the metric adjusted by the 
        `scaling_key` used during the `tl.` step.
    negative_label
        Custom text annotation for the negative side of the x-axis (e.g., "Depleted").
    positive_label
        Custom text annotation for the positive side of the x-axis (e.g., "Enriched").
    fdr_threshold
        Significance threshold used to gray-out non-significant groups.
    exclude_ns
        If `True`, completely removes non-significant groups from the plot instead 
        of graying them out.
    sort_by
        Optional list of group names to enforce a strict vertical plotting order.
    vmin
        Minimum value for the colormap. Can be a float or a percentile string (e.g., "p5").
    vmax
        Maximum value for the colormap. Can be a float or a percentile string (e.g., "p95").
    min_convergence
        Hides any biological group where the GLM convergence rate falls below this float.
    show_convergence
        If `True`, appends the percentage of successfully converged single-cell fits 
        to the y-axis group labels.
    ax
        A matplotlib axes object. If `None`, creates a new figure.
    show
        If `True`, calls `plt.show()`. If `False`, returns the axes object.
    **kwargs
        Additional keyword arguments passed to `seaborn.boxplot`.
    """
    if stat_key not in adata_sc.uns:
        raise KeyError(f"key {stat_key!r} not found in adata_sc.uns.")

    differential_results_dict = adata_sc.uns[stat_key]
    tool_params = differential_results_dict["params"]

    groupby = tool_params.get("groupby", "group")
    batch_key = tool_params.get("batch_key", "sample")
    scaling_key = tool_params.get("scaling_key", None)

    # Classify groups dynamically based on the user-provided FDR threshold
    # to control visual highlighting (graying out non-significant findings).
    results_df = differential_results_dict["results"].assign(
        significance_level=lambda x: [
            f"FDR < {fdr_threshold}" if _ < fdr_threshold else "n.s." for _ in x["fdr"]
        ]
    )

    base_metric = metric.replace("_scaled", "")
    target_metric = (
        f"{base_metric}_scaled" if bias_corrected and scaling_key else base_metric
    )

    if target_metric not in results_df.columns:
        raise KeyError(
            f"metric {target_metric!r} not found in results. Check `bias_corrected` toggle."
        )

    scaled_used_in_plot = target_metric.endswith("_scaled")
    model_params = tool_params.get("model_params", {})
    model_type = model_params.get("model_type", "unknown")

    auto_title = ""
    if model_type == "cox":
        auto_title = model_params.get("duration_col", "time-to-event")
        negative_label = negative_label or "lower risk"
        positive_label = positive_label or "higher risk"
    elif model_type == "glm":
        dep_var = model_params.get("dep_var", "response")
        auto_title = dep_var
        negative_label = negative_label or model_params.get(
            "reference", f"lower {dep_var}"
        )
        positive_label = positive_label or model_params.get(
            "treatment", f"higher {dep_var}"
        )

    negative_label = negative_label or ""
    positive_label = positive_label or ""

    if exclude_ns:
        results_df = results_df[results_df["significance_level"] != "n.s."].copy()
        results_df[groupby] = results_df[groupby].astype(str)

    if "convergence_rate" in results_df.columns:
        results_df[groupby] = results_df[groupby].astype(str)
        convergence_rate_map = (
            results_df.drop_duplicates(groupby)
            .set_index(groupby)["convergence_rate"]
            .to_dict()
        )

        if min_convergence > 0.0:
            results_df = results_df[
                results_df["convergence_rate"] >= min_convergence
            ].copy()

        if show_convergence:
            # Append model convergence rates directly to the group labels so users can
            # visually assess the mathematical trust of each boxplot.
            results_df[groupby] = results_df[groupby].apply(
                lambda g: f"{g} [{convergence_rate_map.get(g, 0):.0%}]"
            )
            if sort_by is not None:
                sort_by = [
                    (
                        f"{g} [{convergence_rate_map.get(g, 0):.0%}]"
                        if g in convergence_rate_map
                        else g
                    )
                    for g in sort_by
                ]

    group_medians_series = results_df.groupby(groupby, observed=True)[
        target_metric
    ].median()

    def _resolve_vlim(val: float | str | None, data: pd.Series, is_min: bool) -> float:
        valid_data = data.dropna()
        if valid_data.empty:
            return -0.1 if is_min else 0.1
        if val is None:
            return float(valid_data.min()) if is_min else float(valid_data.max())
        if isinstance(val, str) and val.startswith("p"):
            return float(np.percentile(valid_data, float(val[1:])))
        return float(val)

    _vmin = _resolve_vlim(vmin, group_medians_series, is_min=True)
    _vmax = _resolve_vlim(vmax, group_medians_series, is_min=False)

    if pd.isna(_vmin) or _vmin >= 0:
        _vmin = -0.1
    if pd.isna(_vmax) or _vmax <= 0:
        _vmax = 0.1
    if _vmin >= _vmax:
        _vmin, _vmax = -0.1, 0.1

    # Anchor the TwoSlopeNorm colormap strictly to zero so divergent biological
    # effects (enrichment vs depletion) are visually symmetric.
    norm = mcolors.TwoSlopeNorm(vmin=_vmin, vmax=_vmax, vcenter=0)
    cmap = sns.color_palette("coolwarm", as_cmap=True)

    non_significant_groups = (
        results_df.loc[results_df["significance_level"] == "n.s.", groupby]
        .unique()
        .tolist()
    )
    group_col_dict = {
        g: (
            "darkgrey"
            if g in non_significant_groups
            else cmap(norm(group_medians_series.loc[g]))
        )
        for g in group_medians_series.index
    }

    order = sort_by or (
        results_df.groupby(groupby, observed=True)[target_metric]
        .agg(["median", "mean"])
        .sort_values(["median", "mean"])
        .index.tolist()
    )

    if ax is None:
        fig, ax = plt.subplots(figsize=(8, 6))

    ax.axvline(x=0, c="grey", linestyle="--", alpha=0.5)

    boxplot_kwargs = dict(linewidth=1, fliersize=1, width=0.8, dodge=False, orient="h")
    boxplot_kwargs.update(kwargs)

    sns.boxplot(
        y=groupby,
        x=target_metric,
        data=results_df,
        order=order,
        hue_order=order,
        ax=ax,
        hue=groupby,
        palette=group_col_dict,
        **boxplot_kwargs,
    )

    ax.text(
        0.0, 1.02, negative_label, ha="left", transform=ax.transAxes, fontsize="medium"
    )
    ax.text(
        1.0, 1.02, positive_label, ha="right", transform=ax.transAxes, fontsize="medium"
    )

    if auto_title:
        ax.set_title(auto_title, pad=25, fontweight="bold")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_ylabel(None)

    # Reconstruct a human-readable axis label from the internal metric tracking string.
    base_metric_clean = (
        metric.replace("median_", "").replace("_scaled", "").replace("_", " ")
    )
    xlabel = f"Median shears {base_metric_clean} per {batch_key}"

    if scaled_used_in_plot and scaling_key:
        if scaling_key == "mRNA_scaling_factor":
            xlabel += "\n(adjusted for mRNA content)"
        else:
            clean_name = scaling_key.replace("_", " ").strip()
            xlabel += f"\n(adjusted by {clean_name})"

    if show_convergence and "convergence_rate" in results_df.columns:
        xlabel += "\n([%] indicates model convergence rate)"

    xlabel = xlabel[0].upper() + xlabel[1:]
    ax.set_xlabel(xlabel)

    if show is False:
        return ax

    plt.show()
    return None


def bulk_detection_limits(
    adata_cohort: AnnData,
    key: str = "bulk_detection_limits",
    *,
    ax: Axes | None = None,
    show: bool | None = None,
    figsize: tuple[float, float] | None = None,
    **kwargs: Any,
) -> Axes | None:
    """
    Plot estimated cell fractions and highlight populations below the detection limit.

    Visualizes the distribution of post-deconvolution fractions across the cohort.
    Populations are ordered by median abundance. Those failing to meet the
    prevalence and abundance thresholds calculated by `tl.flag_bulk_detection_limits`
    are highlighted in red.

    Parameters
    ----------
    adata_cohort
        Annotated data matrix where `.obs` are samples and `.var` are modeled cell groups.
    key
        Key in `adata_cohort.uns` where the detection limit report is stored.
    ax
        A matplotlib axes object. If `None`, creates a new figure.
    show
        Whether to display the plot. If `False`, returns the axis object.
    figsize
        Tuple denoting figure size. Autocalculated if `None`.
    **kwargs
        Additional keyword arguments passed to :func:`seaborn.boxplot`.

    Returns
    -------
    The matplotlib axes object, if `show=False`.
    """
    if key not in adata_cohort.uns:
        raise KeyError(
            f"Key {key!r} not found in adata_cohort.uns. "
            f"Run `tl.flag_bulk_detection_limits` first."
        )

    report = adata_cohort.uns[key]
    params = report["params"]

    layer = params["layer"]
    min_abundance = params["min_abundance"]
    min_samples = params.get("min_samples", params.get("min_patients", 15))
    detected_pops = report["detected_populations"]

    X_fracs = adata_cohort.layers[layer]
    if sp.issparse(X_fracs):
        X_fracs = X_fracs.toarray()

    fractions_df = pd.DataFrame(
        X_fracs, index=adata_cohort.obs_names, columns=adata_cohort.var_names
    )

    median_fracs = fractions_df.median().sort_values(ascending=False)

    if ax is None:
        if figsize is None:
            figsize = (8, max(6, len(fractions_df.columns) * 0.25))
        fig, ax = plt.subplots(figsize=figsize)

    palette = {
        ct: "#2ecc71" if ct in detected_pops else "#e74c3c" for ct in median_fracs.index
    }

    orient = kwargs.pop("orient", "h")

    boxplot_kwargs = dict(linewidth=1, fliersize=1, width=0.8, dodge=False)
    boxplot_kwargs.update(kwargs)

    sns.boxplot(
        data=fractions_df,
        orient=orient,
        order=median_fracs.index,
        palette=palette,
        ax=ax,
        **boxplot_kwargs,
    )

    if orient == "h":
        ax.axvline(
            x=min_abundance,
            color="red",
            linestyle=":",
            linewidth=2.5,
            alpha=0.8,
            label=f"Limit of detection ({min_abundance*100}%)",
        )
        ax.set_xlabel("Shears predicted fraction of bulk sample")
        ax.set_ylabel(None)
    else:
        ax.axhline(
            y=min_abundance,
            color="red",
            linestyle=":",
            linewidth=2.5,
            alpha=0.8,
            label=f"Limit of detection ({min_abundance*100}%)",
        )
        ax.set_ylabel("Shears predicted fraction of bulk sample")
        ax.set_xlabel(None)
        ax.tick_params(axis="x", rotation=45)

    ax.axvline(
        x=min_abundance,
        color="red",
        linestyle=":",
        linewidth=2.5,
        alpha=0.8,
        label=f"Limit of detection ({min_abundance*100}%)",
    )

    var_name = adata_cohort.var.index.name
    group_name = str(var_name) if var_name else "group"

    auto_title = f"Shears {group_name} detection limit\n(Prevalence threshold: ≥ {min_samples} samples)"
    ax.set_title(auto_title, pad=20, fontweight="bold", fontsize="large")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    ax.set_ylabel(None)

    ax.set_xlabel("Shears predicted fraction of bulk sample")
    ax.legend(loc="lower right", frameon=False)

    handles, labels = ax.get_legend_handles_labels()
    unique_labels = dict(zip(labels, handles))
    ax.legend(
        unique_labels.values(), unique_labels.keys(), loc="lower right", frameon=False
    )

    if show is False:
        return ax

    plt.tight_layout()
    plt.show()
    return None
